version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nikolay-records-be"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2bep81nw7sfr"
s3_prefix = "nikolay-records-be"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

